In [ ]:
pip install pandas

In [2]:
import pandas as pd

In [7]:
df = pd.read_csv(r"/Users/Administrator/Downloads/nyc_weather.csv")
df.tail(5)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [32]:
df.Events

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8         Rain
9         Rain
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15        Rain
16    Fog-Snow
17        Snow
18         NaN
19         NaN
20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
30         NaN
Name: Events, dtype: object

In [12]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [14]:
df.WindSpeedMPH

0      8.0
1      7.0
2      8.0
3      9.0
4      5.0
5      4.0
6      2.0
7      4.0
8      8.0
9      NaN
10     NaN
11     6.0
12    10.0
13     5.0
14     5.0
15     7.0
16     6.0
17    12.0
18    11.0
19     6.0
20     6.0
21     NaN
22    16.0
23     6.0
24     3.0
25     7.0
26     7.0
27     5.0
28     8.0
29     7.0
30     5.0
Name: WindSpeedMPH, dtype: float64

In [15]:
df.WindSpeedMPH.isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: WindSpeedMPH, dtype: bool

In [20]:
df.WindSpeedMPH.isna().sum()

np.int64(3)

In [17]:
df.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [21]:
df.count()

EST                     31
Temperature             31
DewPoint                31
Humidity                31
Sea Level PressureIn    31
VisibilityMiles         31
WindSpeedMPH            28
PrecipitationIn         31
CloudCover              31
Events                   9
WindDirDegrees          31
dtype: int64

In [22]:
df.Events.unique()

array([nan, 'Rain', 'Fog-Snow', 'Snow'], dtype=object)

In [23]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [24]:
df.Events.describe()

count        9
unique       3
top       Rain
freq         4
Name: Events, dtype: object

In [25]:
df.Temperature.min()

np.int64(20)

# df1 = df['Temperature']>30
df1

In [28]:
df1.sum()

np.int64(22)

In [29]:
df['EST'][df['Humidity'] == 70]

15    1/16/2016
Name: EST, dtype: object

In [30]:
df['EST'][df['Humidity'] >= 70]

8      1/9/2016
9     1/10/2016
15    1/16/2016
22    1/23/2016
Name: EST, dtype: object

Data Structures in Python

In [34]:
lst = [10,20,30,40,50,60]

#Converting to pandas
s = pd.Series(lst)
print(s,type(s))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64 <class 'pandas.core.series.Series'>

In [36]:
l1 = [1,2,3]
ser = pd.Series(l1,index = ['1st',2,'3rd'],name = 'c1')
print(ser)

1st    1
2      2
3rd    3
Name: c1, dtype: int64

In [37]:
s.loc[0:4]

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [38]:
lst = [10,20,30,40,50,60]
s = pd.Series(lst,dtype = 'float32')
print(s,type(s))

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
dtype: float32 <class 'pandas.core.series.Series'>

In [39]:
s[3]

np.float32(40.0)

In [40]:
s.shape

(6,)

In [41]:
lst = [10,"Roshan",34.56,"Author"]
s = pd.Series(lst,index = ["Stno","Name","Marks","Desg"])
print(s,type(s))

Stno         10
Name     Roshan
Marks     34.56
Desg     Author
dtype: object <class 'pandas.core.series.Series'>

In [42]:
s['Stno']

10

In [44]:
d1 = {"sub1":"Python","sub2":"Java","sub3":"Data Science","sub4":"ML"}
print(d1,type(d1))

{'sub1': 'Python', 'sub2': 'Java', 'sub3': 'Data Science', 'sub4': 'ML'} <class 'dict'>

In [45]:
d1.items()

dict_items([('sub1', 'Python'), ('sub2', 'Java'), ('sub3', 'Data Science'), ('sub4', 'ML')])

In [46]:
d1.keys()

dict_keys(['sub1', 'sub2', 'sub3', 'sub4'])

In [47]:
d1.values()

dict_values(['Python', 'Java', 'Data Science', 'ML'])

In [49]:
s = pd.Series(d1)
print(s)

sub1          Python
sub2            Java
sub3    Data Science
sub4              ML
dtype: object

In [51]:
lst = [[1,3,2,5],[23,415,2,4],[71,94,28,4]]
df = pd.Series(lst)
print(df)

0       [1, 3, 2, 5]
1    [23, 415, 2, 4]
2    [71, 94, 28, 4]
dtype: object

In [52]:
lst = [[10,'RS'],[20,'JG'],[30,'NDA'],[40,'PD']]
df = pd.DataFrame(lst)
print(df)

    0    1
0  10   RS
1  20   JG
2  30  NDA
3  40   PD

In [53]:
df.iloc[1:,:]

    0    1
1  20   JG
2  30  NDA
3  40   PD

In [54]:
df.iloc[3,1]

'PD'

In [56]:
lst = [[10,'RS'],[20,'JG'],[30,'NDA'],[40,'PD']]
df = pd.DataFrame(lst,columns = ['Rno','Name'], index = ['1',20,30,'four'])
print(df)

      Rno Name
1      10   RS
20     20   JG
30     30  NDA
four   40   PD

In [58]:
tpl = (("John",75),("Ryan",35),("Alex",45),("Margot",95),("Jane",25))
df = pd.DataFrame(tpl, index = [1,'d',3,8,1],columns = ['Name','Age'])
print(df)

     Name  Age
1    John   75
d    Ryan   35
3    Alex   45
8  Margot   95
1    Jane   25

In [59]:
df['salary'] = [1,2,3,4,5]

In [60]:
df

     Name  Age  salary
1    John   75       1
d    Ryan   35       2
3    Alex   45       3
8  Margot   95       4
1    Jane   25       5

In [64]:
df.drop('salary',axis = 1,inplace = True)
df

     Name  Age
1    John   75
d    Ryan   35
3    Alex   45
8  Margot   95
1    Jane   25

In [65]:
dictdata = {"Names":["Rose","Gosling","Wayne","Carla"],"Subjects":["Python","Java","C","Pandas"],"Ages":[65,80,85,55]}
print(dictdata)

{'Names': ['Rose', 'Gosling', 'Wayne', 'Carla'], 'Subjects': ['Python', 'Java', 'C', 'Pandas'], 'Ages': [65, 80, 85, 55]}

In [66]:
df = pd.DataFrame(dictdata)
print(df)

     Names Subjects  Ages
0     Rose   Python    65
1  Gosling     Java    80
2    Wayne        C    85
3    Carla   Pandas    55

In [69]:
df = pd.DataFrame(dictdata,index = [1,2,3,'e'])
df

     Names Subjects  Ages
1     Rose   Python    65
2  Gosling     Java    80
3    Wayne        C    85
e    Carla   Pandas    55

In [70]:
l1 = [10,20,30,40]
sdata = pd.Series(l1)
print(type(sdata))
sdata

<class 'pandas.core.series.Series'>

0    10
1    20
2    30
3    40
dtype: int64

In [71]:
df = pd.DataFrame(sdata,columns = ["number"])
df

   number
0      10
1      20
2      30
3      40

In [72]:
df.shape

(4, 1)

In [73]:
type(df)

pandas.core.frame.DataFrame

In [74]:
d1 = {"totmark" : [100,110,120,130],"ExtMarks":[80,75,65,90]}
df = pd.DataFrame(d1,index = [1,2,3,4])
df

   totmark  ExtMarks
1      100        80
2      110        75
3      120        65
4      130        90

In [75]:
df['c3'] = df['totmark'] + df['ExtMarks']
df

   totmark  ExtMarks   c3
1      100        80  180
2      110        75  185
3      120        65  185
4      130        90  220

In [76]:
df['sub'] = df['totmark'] - df['ExtMarks']

In [77]:
df

   totmark  ExtMarks   c3  sub
1      100        80  180   20
2      110        75  185   35
3      120        65  185   55
4      130        90  220   40

In [78]:
df['new column'] = [1,2,3,4]
df['new data'] = ['1st','2nd','3rd','4th']
df

   totmark  ExtMarks   c3  sub  new column new data
1      100        80  180   20           1      1st
2      110        75  185   35           2      2nd
3      120        65  185   55           3      3rd
4      130        90  220   40           4      4th

In [80]:
df['Roll_no'] = range(1,5)
df

   totmark  ExtMarks   c3  sub  new column new data  Roll_no
1      100        80  180   20           1      1st        1
2      110        75  185   35           2      2nd        2
3      120        65  185   55           3      3rd        3
4      130        90  220   40           4      4th        4

In [82]:
df = df[['Roll_no','totmark','ExtMarks','new data']]
df

   Roll_no  totmark  ExtMarks new data
1        1      100        80      1st
2        2      110        75      2nd
3        3      120        65      3rd
4        4      130        90      4th

In [83]:
df1 = df[['Roll_no','totmark']]
df1

   Roll_no  totmark
1        1      100
2        2      110
3        3      120
4        4      130

In [85]:
df = df.drop(columns = ['sub'],axis = 1)
df

KeyError: "['sub'] not found in axis"

In [86]:
df = df.sort_values(["ExtMarks"],ascending = True)
df

   Roll_no  totmark  ExtMarks new data
3        3      120        65      3rd
2        2      110        75      2nd
1        1      100        80      1st
4        4      130        90      4th

In [90]:
df = pd.read_csv(r"/Users/Administrator/Downloads/ipl.csv")
df.tail(5)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [88]:
pip install scipy

Collecting scipy
  Downloading scipy-1.15.2-cp311-cp311-win_amd64.whl (41.2 MB)
     --------------------------------------- 41.2/41.2 MB 12.3 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\program files\python311\lib\site-packages (from scipy) (2.2.5)
Installing collected packages: scipy
Successfully installed scipy-1.15.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [92]:
df.sort_values(['team1'],ascending = True)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
754,1181767,Visakhapatnam,2019-05-10,F du Plessis,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN,BNJ Oxenford,S Ravi
745,1178425,Chennai,2019-05-01,MS Dhoni,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Chennai Super Kings,runs,80.0,N,NaN,AY Dandekar,Nitin Menon
92,392217,Kimberley,2009-05-09,S Badrinath,De Beers Diamond Oval,1,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Chennai Super Kings,wickets,7.0,N,NaN,GAV Baxter,HDPK Dharmasena
212,501236,Chennai,2011-05-01,JA Morkel,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,bat,Chennai Super Kings,runs,19.0,N,NaN,Aleem Dar,RB Tiffin
89,392214,Centurion,2009-05-07,ML Hayden,SuperSport Park,1,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Chennai Super Kings,runs,12.0,N,D/L,DJ Harper,TH Wijewardene
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,829799,Hyderabad,2015-05-11,DA Warner,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,5.0,N,NaN,AK Chaudhary,HDPK Dharmasena
508,829807,Hyderabad,2015-05-15,V Kohli,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,wickets,6.0,N,D/L,AK Chaudhary,HDPK Dharmasena
728,1178408,Hyderabad,2019-04-17,DA Warner,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,bat,Sunrisers Hyderabad,wickets,6.0,N,NaN,UV Gandhe,IJ Gould
389,598065,Hyderabad,2013-05-17,A Mishra,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,23.0,N,NaN,Asad Rauf,AK Chaudhary
324,598000,Hyderabad,2013-04-05,A Mishra,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Pune Warriors,Pune Warriors,field,Sunrisers Hyderabad,runs,22.0,N,NaN,S Ravi,SJA Taufel

In [93]:
df.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [94]:
df.isnull()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
812,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
813,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
814,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
815,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB